name: 'Textile Bucket Push'
description: 'Create, update, destroy folders on IPFS, IPNS and HTTP.'
author: 'textile.io'
branding:
  icon: 'type'  
  color: 'blue'
inputs:
  key:
    description: 'Textile Hub Account Key.'
    required: true
  secret:
    description: 'Textile Hub Account Secret.'
    required: true
  thread:
    description: 'Existing account ThreadID.'
    required: true
  bucket:
    description: 'Bucket name.'
    required: true
  path:
    description: 'Path to Bucket root.'
    default: '.'
  pattern:
    description: 'File pattern matching.'
    default: '**/*'
outputs:
  ipfs:
    description: 'IPFS Address'
  ipfsLink:
    description: 'Public gateway IPFS link'
  ipns:
    description: 'IPNS Key'
  ipnsLink:
    description: 'Public gateway IPNS link'
  http:
    description: 'HTTP link to Textile Hub'
runs:
  using: 'node12'
  main: 'dist/index.js'
