name: 'Textile Buckets'
description: 'Create, update, destroy folders on IPFS, IPNS and HTTP.'
author: 'textile.io'
branding:
  icon: 'type'  
  color: 'blue'
inputs:
  key:
    description: 'Textile Hub Account Key.'
    required: true
  secret:
    description: 'Textile Hub Account Secret.'
    required: true
  thread:
    description: 'Existing account ThreadID.'
    required: true
  bucket:
    description: 'Bucket name.'
    required: true
  path:
    description: 'Path to Bucket root.'
    default: '.'
  pattern:
    description: 'File pattern matching.'
    default: '**/*'
  remove:
    description: 'Remove the bucket by name (WARNING).'
    default: 'false'
outputs:
  ipfs:
    description: 'IPFS Address'
  ipns:
    description: 'IPNS Link'
  url:
    description: 'Public gateway URL'
  www:
    description: 'HTTP link on Textile Hub'
runs:
  using: 'node12'
  main: 'dist/index.js'
