name: 'Textile Buckets'
description: 'Create, update, destroy folders on IPFS, IPNS and HTTP.'
author: 'textile.io'
branding:
  icon: 'type'  
  color: 'blue'
inputs:
  key:
    description: 'Textile Hub Account Key.'
    required: true
  secret:
    description: 'Textile Hub Account Secret.'
    required: true
  thread:
    description: 'Existing account ThreadID.'
    required: true
  bucket:
    description: 'Bucket name.'
    required: true
  path:
    description: 'Path to Bucket root.'
    default: '.'
  pattern:
    description: 'File pattern matching.'
    default: '**/*'
  remove:
    description: 'Remove the bucket by name (WARNING).'
    default: 'false'
outputs:
  key:
    description: 'Bucket Key'
  ipfs:
    description: 'IPFS CID'
  ipfsUrl:
    description: 'IPFS Gateway URL'
  ipns:
    description: 'IPNS Address'
  ipnsUrl:
    description: 'IPNS Gateway URL'
  hub:
    description: 'Thread-Bucket URL on the Hub'
  www:
    description: 'WWW Domain URL'
runs:
  using: 'node12'
  main: 'dist/index.js'
